- name: Initialize Kubernetes cluster
  command:
    cmd: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU,Mem

- name: Set up kubeconfig for regular user
  file:
    path: "$HOME/.kube"
    state: directory
    mode: '0755'

- name: Copy admin kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "$HOME/.kube/config"
    remote_src: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: '0600'

- name: Deploy CNI networking (example with Flannel)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', 'https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml') | from_yaml }}"

- name: Generate token for worker nodes
  command:
    cmd: kubeadm token create --print-join-command
  register: join_command

- name: Save join command to a file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join_command.sh
    mode: '0644'