---
- name: Install Jenkins on Ubuntu 24
  hosts: jenkins_server
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install dependencies
      apt:
        name:
          - openjdk-17-jdk
          - ca-certificates
          - apt-transport-https
          - wget
        state: present

    - name: Add Jenkins repository key
      shell: |
        wget -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        create: yes

    - name: Update package lists after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Verify Jenkins is running
      command: systemctl status jenkins
      register: jenkins_status
      changed_when: false

    - name: Display Jenkins status
      debug:
        msg: "{{ jenkins_status.stdout_lines }}"