- hosts: jenkins_servers
  become: true # Use sudo or equivalent privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://get.jenkins.io/stable/ debian/
        state: present
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started