    - name: Update APT package index and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins apt repository
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/

    - name: Update APT after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Get initial Jenkins admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Show initial Jenkins admin password
      debug:
        msg: "Initial Jenkins password is: {{ jenkins_admin_password['content'] | b64decode }}"