- name: Copy join command from master
  fetch:
    src: /home/ubuntu/join.sh
    dest: /tmp/join.sh
    flat: yes
  delegate_to: master_node

- name: Transfer join command to worker
  copy:
    src: /tmp/join.sh
    dest: /home/ubuntu/join.sh
    mode: 0755

- name: Join Kubernetes cluster
  command: bash /home/ubuntu/join.sh
